#!/bin/sh
WORKDIR="/tmp"
LATEST_RELEASE=""
if [ $# -eq 0 ]
  then
	LATEST_RELEASE=$(curl https://api.github.com/repos/hashicorp/terraform/releases/latest | jq --raw-output '.tag_name' | cut -c 2-)
  else
	LATEST_RELEASE=$1
fi
if [ "$(terraform --version | grep -oP -m 1  '[0-9]+\.[0-9]+\.[0-9]+' | tr -d ' ')" != ${LATEST_RELEASE} ] 
	then
		echo "Installing Terraform ${LATEST_RELEASE}..."
		sudo rm /usr/local/bin/terraform
		wget https://releases.hashicorp.com/terraform/${LATEST_RELEASE}/terraform_${LATEST_RELEASE}_linux_amd64.zip
		unzip terraform_${LATEST_RELEASE}_linux_amd64.zip
		sudo mv terraform /usr/local/bin/terraform
		rm terraform_${LATEST_RELEASE}_linux_amd64.zip
	else
		echo "Version ${LATEST_RELEASE} already installed"
fi
